services:
  word2html:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_REGISTRY_MIRROR=docker.1ms.run/library/python:3.11-slim
    container_name: word2html-converter
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - FLASK_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s